<?php

function react_embed_preprocess_block(&$variables)
{
  if ($variables['plugin_id'] == "react_app_block") {
    $base_path = drupal_get_path('module', 'react_embed');
    $raw = file_get_contents($base_path'/data.config.json');
    $data_conf = json_decode($raw);
    var_dump(drupal_get_path('module', 'react_embed'));
    $variables['content']['#attached']['drupalSettings']['reactApp']['data'] = $data_conf;
  }
}
