<?php

function react_embed_preprocess_block(&$variables)
{
  if ($variables['plugin_id'] == "react_app_block") {
    $raw = file_get_contents(drupal_get_path('module', 'react_embed') . '/data.config.json');
    $data_conf = json_decode($raw);
    $data = array();
    foreach ($data_conf as $conf) {
      $block = \Drupal\block_content\Entity\BlockContent::load($conf->block_id);
      foreach ($conf->fields as $field) {
        if($field->name === "default"){
          $variables['content']['#attached']['drupalSettings']['drupalData'][$field] = $block->get($field)->getValue()[0]['value'];

        }
      }
    }
  }
}
