<?php

use Drupal\media\Entity\Media;
use \Drupal\block_content\Entity\BlockContent;

function toCamelCase($value)
{
  return str_replace('_', '', lcfirst(ucwords($value, '_')));
}

function react_embed_preprocess_block(&$variables)
{
  if ($variables['plugin_id'] == "react_app_block") {
    $raw = file_get_contents(drupal_get_path('module', 'react_embed') . '/data.config.json');
    $data_conf = json_decode($raw);
    $data = array();
    foreach ($data_conf as $conf) {
      $block = BlockContent::load($conf->block_id);
      foreach ($conf->fields as $field) {
        switch ($field->type) {
          case 'default':
            $variables['content']['#attached']['drupalSettings']['drupalData'][$conf->name][toCamelCase($field->name)] = $block->get($field->name)->getValue()[0]['value'];
            break;

          case 'media':
            $media = Media::load($block->get($field->name)->getString());
            $uri = $media->field_media_image->entity->getFileUri();
            $variables['content']['#attached']['drupalSettings']['drupalData'][$conf->name][toCamelCase($field->name)] = file_create_url($uri);
            break;
          default:
            # code...
            break;
        }
      }
    }
  }
}
