<?php

function react_embed_preprocess_block(&$variables)
{
  if ($variables['plugin_id'] == "react_app_block") {
    $raw = file_get_contents(drupal_get_path('module', 'react_embed') . '/data.config.json');
    $data_conf = json_decode($raw);
    $data = array();
    foreach ($data_conf as $conf) {
      $block = \Drupal\block_content\Entity\BlockContent::load($conf->block_id);
      foreach ($conf->fields as $field) {
        switch ($field->name) {
          case 'default':
            $variables['content']['#attached']['drupalSettings']['drupalData'][$field] = $block->get($field)->getValue()[0]['value'];
            break;
          
          case 'media':
            $media_field = $node_load->get('media_field_machine_name')->getString(); // Get media ID from your field. 
            $media_entity_load = Media::load($media_field); // Loading media entity.
            $uri = $media_entity_load->field_media_video_file->entity->getFileUri(); // It is for image media.
            $media_url = file_create_url($uri); // Here you will get URL of 
            break;
          default:
            # code...
            break;
        }
        if($field->name === "default"){
          $variables['content']['#attached']['drupalSettings']['drupalData'][$field] = $block->get($field)->getValue()[0]['value'];
        }else
      }
    }
  }
}
